### ISSUE TITLE
THANK YOU!!!!!!!!!

### ISSUE THREAD

**Issue by remotevase** [TesseractTeam/ImagicalMine#1]
THANK YOU SO MUCH!

**Comment by dterweij** [comment]
It is stupid :) Just  keep the code at one place, instead of moving arround. The code is scattered all over github and just a few people are actualy coding something usefull. All those people from different forks and repositories should be at one repository and coding. Then we, users, get a good working MCPE server with a lot features and bugfixes. Besides that, i think we get a faster server release on new protocols (read: new majongh versions). 
So gather all the active MCPE coders to one repository and delete all the other shit.. euh forks and clones :)

Happy new year ....

**Comment by remotevase** [comment]
@dterweij i totally agree with you. There are a few understandable problems. 
1. @dktapps hates many developers other than his own little group of coders 
2. Not everybody codes PHP 
3. Not everybody codes the same language 
4. Many people dislike it when one person had authority over another.

On the other hand: Some of the spoons are very friendly to each other, then we can join those two organizations and make an awesome one. Aka tesseract+Elywing

**Comment by dktapps** [comment]
> @dktapps hates many developers other than his own little group of coders

Not true. I just dislike people who don't learn from mistakes.

**Comment by remotevase** [comment]
I see... Hmm... Okay then, that would be most of us. Most of us try one thing, fail, try another, fail, and finally try another and succeed. Most of us learn from our success as to what code works, and learn from our failures what code doesn't.

**Comment by keithkfng** [comment]
I find it amusing how people pick up an abandoned project and continue to work on it even though the code is so messed up and not worth the time...

**Comment by remotevase** [comment]
yeah! I find it amusing! But for a good reason! It shows that people have determination and that people love the project!
